[package]
name = "example_app"

version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rerun = { workspace = true }
re_control_panel = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
